version: "3"
services:
  web: 
      container_name: contenedor-nginx
      image: nginx
      build: .
      ports:
            - "80:80"
      depends_on:
                 - mysql
      restart: always

  mysql:
      container_name: contenedor-sql
      image: mysql:latest
      restart: "no"
