version: "3"
services:
  web: 
      container_name: container-nginx
      image: nginx
      build:
             context: 2BDOCFILE
             dockerfile: Dockerfile
      ports:
             - "80:80"
      depends_on:
             - mysql
      restart: always

  mysql:
      container_name: container-sql
      image: mysql:latest
      restart: "no"
